version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"        # Puerto de RabbitMQ
      - "15672:15672"      # Panel de administración

  users_service:
    build:
      context: ./backend/users_service
      dockerfile: Dockerfile
    container_name: users-service
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8000:8000"

  notifications_service:
    build:
      context: ./backend/notifications_service
      dockerfile: Dockerfile
    container_name: notifications-service
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
